# Generated by Django 2.0.4 on 2019-02-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chara_name', models.CharField(max_length=20, verbose_name='キャラ名')),
                ('title', models.CharField(max_length=30, verbose_name='作品名')),
            ],
        ),
    ]
